name: 'GitHub Actions Weather Bot' 

on: 
  push:
  schedule:
  # 定时任务，在每天的5点推送天气信息到邮箱 
    - cron: '0 0,4,9,13 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
    # 首先copy git仓库到虚拟机上
      - name: 'Checkout codes'
        uses: actions/checkout@v1
    # 执行仓库中的脚本文件
      - name: 'Get Weather'
        run: bash ./weather.sh
    # 获取格式化的日期并存入GitHub内置的环境变量中
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
    # 使用现成的发送邮箱的GitHub action来发送邮件
      - name: Send mail
        uses: dawidd6/action-send-mail@master
        with:
          # Reqired mail server address 
          server_address: smtp.mxhichina.com
          # Optional Server port, default 25 (if server_port is 465 this connection use TLS)
          server_port: 465
          # Optional (recommended): mail server username
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended): mail server password
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject
          subject: GitHub Actions 天气预报 (${{env.REPORT_DATE}})
          # Required recipients address
          #to: alice@example.com, bob@example.com
          to: san@ahome.lovestoblog.com
          # Required sender full name (address can be skipped)
          #from: alice # <alice@example.com>
          from: San # <san@ahome.lovestoblog.com>
          # Optional plain body
          #body: Build job of ${{github.repository}} completed successfully!
          # Optional HTML body read from file
          html_body: file://result.html
          # Optional carbon copy recipients
          #cc: a@example.com,b@example.com
          # Optional blind carbon copy recipients
          #bcc: c@example.com,d@example.com
          # Optional recipient of the email response
          #reply_to: luke@example.com
          # Optional Message ID this message is replying to
          #in_reply_to: <random-luke@example.com>
          # Optional converting Markdown to HTML (set content_type to text/html too)
          #convert_mardown: true
          # Optional attachments
          #attachments: README.md
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: low
